# Generated by Django 5.0.6 on 2024-06-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_usermadel_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermadel',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
