# Generated by Django 5.0.6 on 2024-06-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_usermadel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('image', models.ImageField(null=True, upload_to='media/chef/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=200, verbose_name='Narxi')),
                ('description', models.TextField(max_length=300, verbose_name='Mahsulot haqida')),
                ('category_code', models.CharField(max_length=200, verbose_name='Kategoriya kodi')),
                ('category_name', models.CharField(max_length=200, verbose_name='Category Nomi')),
                ('subcategory_code', models.CharField(max_length=34, verbose_name='Ost-kategoriya kodi')),
                ('subcategory_name', models.CharField(max_length=30, verbose_name='Ost-kategoriya nomi')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
