# Generated by Django 5.0.6 on 2024-06-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentBlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(auto_created=True)),
                ('creator', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='media/recentblog/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='media/product/'),
        ),
    ]
