# Generated by Django 5.0.6 on 2024-06-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_recentblogmodel_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentblogmodel',
            name='create_data',
            field=models.DateField(auto_created=True),
        ),
    ]
