# Generated by Django 5.0.6 on 2024-06-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_teammodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('create_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
