# Generated by Django 5.0.6 on 2024-06-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
                ('email', models.EmailField(max_length=32)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
