# Generated by Django 5.0.6 on 2024-06-17 14:30

import web.helps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to=web.helps.SaveModelFields.product_image_path),
            preserve_default=False,
        ),
    ]
